global:
  scrape_interval: 8h
  evaluation_interval: 1m
  scrape_timeout: 7h30m  

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'telegram-bot'
    static_configs:
      - targets: ['telegram-bot:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s  